### ISSUE TITLE
DataModel

### ISSUE THREAD

**Issue by forginater** [CapSap/apaMakan#1]
## TODO
- [x] Branch: dataStructures
- [x] Clear App Component
- [x] Implement Data Model for recipes in App
- [x] Create component files & render in App
- [x] Review and agree on good names to use in our data model

##Basic Component Hierarchy
App
|__Home
|__Recipe
|__Nav
