### ISSUE TITLE
Test Dummy Data & Pass Recipe Props from BottomTabs.Navigator to Home Screen

### ISSUE THREAD

**Issue by forginater** [CapSap/apaMakan#14]
## TODO
- [x] Test Dummy Data in Home with type signatures
- [x] Render Dummy Data in App
- [x] Cleanup Testing Code
- [x] Move types into own file
- [x] Pass recipeData from BottomTabsNavigator to HomeScreen using initialProps 
- [x] Pass recipeData from BottomTabsNavigator to RecipeScreen using initialProps
