### ISSUE TITLE
Create a ModifyRecipe screen and add add it the the BottomTab.navigator

### ISSUE THREAD

**Issue by forginater** [CapSap/apaMakan#18]
## Overview
Add a ModifyRecipe tab.screen that has the ability to delete recipes

## TODO
- [x] Create a ModifyRecipe screen
- [x] add it the the BottomTab.navigator
- [x] Start with importing dummyData locally into ModifyRecipe, store it in useState and add ability to delete a recipe
- [x] Make sure removal updating between screens
- [x] Display list of selectable list of recipes with a button to remove the selected recipe

## NOTE for future
>currently using id property of dummyData as unique key prop... if our recipesState is changing ideally ensure that those keys remain unique, perhaps using a hashing function or UUID library to generate ids 
>Not sure on downsides of using map, in front masters I believe they said FlatList is better optimised than map() function in react native
