### ISSUE TITLE
Pass and update state through route.params 

### ISSUE THREAD

**Issue by forginater** [CapSap/apaMakan#19]
##Overview
Dynamically store recipes data such that changes are synchronised between different screens when recipes data changes... Try with passing state & setState through route.params

## TODO
- [x] Test passing functions through params & add LogBox to remove warning
- [x] Render result of dummy function
- [x] setState functions through route.params to change state.
- [x]  Check that state changes to recipes work with react navigation and that these changes are synchronised between screens
- [x] Decide on an alterative model. Options: (1) Share context between adjacent screens with useContext (2) use a state management library such as redux

####NOTES:

> Apparently passing functions through routes.param is an anti pattern, params need to be serializable which I believe shouldn't be an issue for basic setState functions
> According to the docs "If you don't use state persistence or deep link to the screen which accepts functions in params, then the warning doesn't affect you and you can safely ignore it. To ignore the warning, you can use LogBox.ignoreLogs."
> Nothing preventing you from passing the function! It will only print a warning to remind you that these Params are not serializable

####Result of passing and updating state through route.params

> Implemented a testHook with a counter, able to pass through both the state and the setState function through route.params... However, calling setState in the screen doesn't trigger the RecipeScreen to rerender with updated initialParams with new useState value so the initial value persists.... By making the name of RecipeScreen dynamic with a reference to state value, able to force the recipeScreen to rerender with updated initialParams... This is a total hack, forces user back to homescreen and probably a good indication that useContext is a far better solution
