### ISSUE TITLE
Implement useContext() solution: 

### ISSUE THREAD

**Issue by forginater** [CapSap/apaMakan#21]
## Overview

Dynamically store recipes data such that changes are synchronised between different screens when recipes data changes

## TODO
- [x] Cleanup route.params type 
- [x] Create context provider
- [x] Wrap navigator in Context Provider in App
- [x] Access Context in screens
- [x] Wrap state in context 
- [x] Pass setState to useContext hook 
- [x] Update state & check synchronises between adjacent screens
- [x] Test functionality
