### ISSUE TITLE
Add Recipes implemenet

### ISSUE THREAD

**Issue by forginater** [CapSap/apaMakan#24]
## Overview
- The aim is to make the ModifyRecipeScreen toggle between 'Remove' and 'Add' functionality. 
- In 'Add' mode user can see some recipes not currently in app state, select a recipe and click Add which will update the recipes stored in AppState. 

### Rationale and optional features to add later
- While the code is messy atm my objective is to make the basic functionality reusable (1) listing a selectable object (2) Applying a modification to selected object(s) that's defined outside of the JSX component
- If we had a database of available recipes, could add a 'Search' feature such that the user can enter a string and the resulting list of available recipes would be filtered based on search query (basic implementation could just use a regular expression). This could also be used to create and edit a favouriteRecipes object that's attacked to a profile

## TODO
- [x] put JSX in a different component and make it reusable.. so it can be selected for Adding & Removing
- [x] Create some dummy data for new recipes
- [x] State and toggle functionality for changing modification mode
- [x] Test to make sure updating in other screens 
- [ ] clean up the code, in particular, figure out how to define the handlers entirely at the highest level (outside of DisplayRecipeModifier) without accessing stale data
- [ ] generate a UUID for any new recipes added to recipesData in App to ensure unique key
